// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type CarCreateInput struct {
	Model string `json:"model"`
}

type CarsToUserInput struct {
	CarIDs []string `json:"carIDs"`
	UserID string   `json:"userID"`
}

type GenericResponse struct {
	Status string `json:"status"`
}

type GroupCreateInput struct {
	Name string `json:"name"`
}

type UserCreateInput struct {
	Age  int     `json:"age"`
	Name *string `json:"name"`
}

type UsersToGroup struct {
	UserIDs []string `json:"userIDs"`
	GroupID string   `json:"groupID"`
}
