// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type CarCreateInput struct {
	Model string `json:"model,omitempty"`
}

type CarsToUserInput struct {
	CarIDs []string `json:"carIDs,omitempty"`
	UserID string   `json:"userID,omitempty"`
}

type GenericResponse struct {
	Status string `json:"status,omitempty"`
}

type GroupCreateInput struct {
	ID     string  `json:"ID,omitempty"`
	Name   string  `json:"name,omitempty"`
	Parent *string `json:"Parent,omitempty"`
}

type UserCreateInput struct {
	Age         int      `json:"age,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

type UsersToGroup struct {
	UserIDs []string `json:"userIDs,omitempty"`
	GroupID string   `json:"groupID,omitempty"`
}
